version: '3.8'

services:
  # Service pour PostgreSQL
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-FakeTwitterBDD}
      POSTGRES_USER: ${POSTGRES_USER:-root}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!root!}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-FakeTwitterBDD}", "-U", "${POSTGRES_USER:-root}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - 5432:5432
      

  # Service pour PHP avec Symfony
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_php
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - database
  web:
    image: httpd:2.4
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/web/httpd.conf:/usr/local/apache2/conf/httpd.conf
    depends_on:
      - php
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html/public


volumes:
  database_data:
